### ISSUE TITLE
константы

### ISSUE THREAD

**Issue by paulin-mipt** [squantus/GameOfLife#4]
В graphics.py явно хочется вынести все цвета и fps в константы в отдельном файле (или просто наверху того же файла), чтобы не искать их по файлу, когда захочется поменять цветовую схему

**Comment by squantus** [comment]
Пришлось немного схитрить с лямбдами(ничего лучше и компактней не придумал), зато водичка все еще переливается) Пойдет?

**Comment by paulin-mipt** [comment]
Лямбды вполне хороши. Вообще мне всё нравится, только я бы поработала с репозиторием:
- Убрать папки idea и pycache
- Написать README.md с примером запуска программы (может быть, загрузить в репозиторий какой-нибудь годный пример исходного поля?)
